### PR TITLE
Overwrite Progress Bars instead of printing each iteration

### PR DESCRIPTION
**Pull request by DrJKL**
Update tqdm calls to overwrite a single line
This leads to less console spam.
Also use the tqdm for the image update notifications (I think the math on this is wrong, please check)

### CODE REVIEW

**Comment by lucidrains** [comment]
@DrJKL thank Alexander! can you possibly deal with the merge conflicts?

**Comment by DrJKL** [comment]
Okay, that was easy :-)

**Comment by lucidrains** [comment]
@DrJKL sorry but i reverted that commit, is it too much to ask you to also revert back to what you had before? 🙏

**Comment by DrJKL** [comment]
For you Phil, not a problem

**Comment by DrJKL** [comment]
How's that?

**Comment by lucidrains** [comment]
yolo

**Pull request merged**
