### PR TITLE
Fix helps use long texts.

### PR DESCRIPTION
**Pull request by forkbabu**
Code breaks with long Texts

### CODE REVIEW

**Comment by lucidrains** [comment]
@forkbabu ohh, wouldn't this just make the first word the filename?

**Comment by lucidrains** [comment]
@forkbabu what is the maximum filename length for your OS? i'll just put a hard limit

**Comment by forkbabu** [comment]
@lucidrains it crashed while using "For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord."  on Google Colab (Ubuntu 18.02LTS)

**Comment by lucidrains** [comment]
@forkbabu do you want to try https://github.com/lucidrains/big-sleep/releases/tag/0.4.4

**Pull request closed without merging**
